name: cs5670_python_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.0
  - numpy=1.26.4
  - pillow=10.2.0
  - opencv=4.6.0
  - pyparsing=2.4.7
  - python=3.9.7
  - pyttk=0.3.2
  - scipy=1.11.4
  - tk=8.6.10


